export default function TermsPage() {
  return (
    <main style={{ maxWidth: "1000px", margin: "70px auto", padding: "30px" }}>
      <h1>Terms and Conditions</h1>

      <p>
        These Terms and Conditions (“Terms”) govern your access to and use of CPA
        Niche Scout AI. By accessing or using the service, you agree to be legally
        bound by these Terms.
      </p>

      <h2>1. Description of Service</h2>
      <p>
        CPA Niche Scout AI is a software platform designed to provide analytical
        and informational tools related to CPA and affiliate niche research.
        Outputs generated by the software are informational in nature and do not
        constitute professional advice.
      </p>

      <h2>2. No Earnings Guarantees</h2>
      <p>
        We make no representations or warranties regarding earnings, profits, or
        outcomes. Any results depend on numerous external factors beyond our
        control.
      </p>

      <h2>3. User Responsibilities</h2>
      <p>
        You agree to use the service lawfully and not to:
      </p>
      <ul>
        <li>Bypass or manipulate usage limits or credit systems</li>
        <li>Reverse engineer or exploit the platform</li>
        <li>Interfere with system security or availability</li>
        <li>Use the service for unlawful or deceptive purposes</li>
      </ul>

      <h2>4. Access and Availability</h2>
      <p>
        We reserve the right to modify, suspend, or discontinue any aspect of the
        service at any time, with or without notice.
      </p>

      <h2>5. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, CPA Niche Scout AI shall not be
        liable for any direct, indirect, incidental, or consequential damages
        arising from the use or inability to use the service.
      </p>

      <h2>6. Governing Agreement</h2>
      <p>
        These Terms constitute the entire agreement between you and CPA Niche
        Scout AI regarding use of the service.
      </p>
    </main>
  );
}
