export default function DisclaimerPage() {
  return (
    <main style={{ maxWidth: "800px", margin: "40px auto", padding: "20px" }}>
      <h1>Disclaimer</h1>

      <p>
        CPA Niche Scout AI is an informational research tool. We do not provide
        financial, legal, or business advice.
      </p>

      <p>
        Any examples or outputs generated by the software are for educational
        purposes only.
      </p>

      <p>
        Earnings in CPA and affiliate marketing vary widely and depend on many
        factors including experience, effort, traffic sources, and market
        conditions.
      </p>

      <p>
        We make no guarantees of income or success.
      </p>
    </main>
  );
}
